Feature/gaia 3067
leftshiftone/canon pull request #50
Opened 2021-06-16 10:57 UTC by ptrcc

2021-06-16 11:26 UTC, aemaem requested changes

2021-06-16 11:26 UTC, aemaem commented on src/main/resources/xml/canon.xsd
> +        <xs:attribute type="xs:integer" name="zoomByRadius"/>
Wie so ist das im xsd ein integer und im Objekt ein String? Sollte hier dann auch ein String sein, oder?

2021-06-16 12:01 UTC, aemaem approved these changes

2021-06-21 05:17 UTC, Nerminas approved these changes

2021-06-21 06:54 UTC, merged